# ------------------------------------------
# Action for Alisher lesson one
#
# Copyleft (c) by Alexander Shidlovsky 2021.
# ------------------------------------------

name: level1_pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Git clone repo
        uses: actions/checkout@v2

      - name: Build project
        run: echo Hello, world!

  tests:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Git clone repo
        uses: actions/checkout@v2

      - name: Test project
        run: echo Hello, world!

  run:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - name: Git clone repo
        uses: actions/checkout@v2

      - name: Run project
        run: echo Hello, world!
