# ------------------------------------------
# Action for Alisher lesson one
#
# Copyleft (c) by Alexander Shidlovsky 2021.
# ------------------------------------------

name: level1_pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Git clone repo
        uses: actions/checkout@v2

      - name: Build project
        run: cd Alisher_level_1/ && mkdir build && cd build && cmake .. && make


  tests:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Git clone repo
        uses: actions/checkout@v2

      - name: Build project
        run: cd Alisher_level_1/ && mkdir build && cd build && cmake .. && make

      - name: Test project
        run: cd test/ && ./tests